**What is ANN?**

Artificial Neural Networks (ANN) is a supervised learning system built of a large number of simple elements, called neurons or perceptrons. Each neuron can make simple decisions, and feeds those decisions to other neurons, organized in interconnected layers.

**What is Activation Function?**

If we do not apply a Activation function then the output signal would simply be a simple linear function.A linear function is just a polynomial of one degree.

- Sigmoid
- Tanh
- ReLu
- LeakyReLu
- SoftMax

**Steps for building your first ANN**

- Data Preprocessing
- Add input layer
- Random w init
- Add Hidden Layers
- Select Optimizer, Loss, and Performance Metrics
- Compile the model
- use model.fit to train the model
- Evaluate the model
- Adjust optimization parameters or model if needed

- pip install tensorflow==2.0.0-rc0   for CPU.............
- pip install tensorflow-gpu==2.0.0-rc0   for GPU

**Importing the Library**

In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten, Dense 

In [0]:
import pandas as pd
import numpy as np

In [0]:
# Load the dataset
df2 = pd.read_csv('Customer_Churn_Modelling.csv')

In [8]:
df2.head(10)  # Print first 10 data.

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0
5          6    15574012       Chu  ...               0       149756.71      1
6          7    15592531  Bartlett  ...               1        10062.80      0
7          8    15656148    Obinna  ...               0       119346.88      1
8          9    15792365        He  ...               1        74940.50      0
9         10    15592389        H?  ...               1        71725.73      0

[10 rows x 14 columns]

In [0]:
X = df2.drop(labels=['CustomerId', 'Surname', 'RowNumber', 'Exited'], axis = 1)
y = df2['Exited']

In [11]:
X.head(10)

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France  Female  ...          1               1        101348.88
1          608     Spain  Female  ...          0               1        112542.58
2          502    France  Female  ...          1               0        113931.57
3          699    France  Female  ...          0               0         93826.63
4          850     Spain  Female  ...          1               1         79084.10
5          645     Spain    Male  ...          1               0        149756.71
6          822    France    Male  ...          1               1         10062.80
7          376   Germany  Female  ...          1               0        119346.88
8          501    France    Male  ...          0               1         74940.50
9          684    France    Male  ...          1               1         71725.73

[10 rows x 10 columns]

In [12]:
y.head(10)

0    1
1    0
2    1
3    0
4    0
5    1
6    0
7    1
8    0
9    0
Name: Exited, dtype: int64

***Convert Categorical Data into Numerical Data***

In [0]:
from sklearn.preprocessing import LabelEncoder

In [0]:
label1 = LabelEncoder()
X['Geography'] = label1.fit_transform(X['Geography'])

In [15]:
X.head(10)

CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0  Female  ...          1               1        101348.88
1          608          2  Female  ...          0               1        112542.58
2          502          0  Female  ...          1               0        113931.57
3          699          0  Female  ...          0               0         93826.63
4          850          2  Female  ...          1               1         79084.10
5          645          2    Male  ...          1               0        149756.71
6          822          0    Male  ...          1               1         10062.80
7          376          1  Female  ...          1               0        119346.88
8          501          0    Male  ...          0               1         74940.50
9          684          0    Male  ...          1               1         71725.73

[10 rows x 10 columns]

In [16]:
label = LabelEncoder()
X['Gender'] = label.fit_transform(X['Gender'])
X.head()

CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0       0  ...          1               1        101348.88
1          608          2       0  ...          0               1        112542.58
2          502          0       0  ...          1               0        113931.57
3          699          0       0  ...          0               0         93826.63
4          850          2       0  ...          1               1         79084.10

[5 rows x 10 columns]

In [17]:
X = pd.get_dummies(X, drop_first=True, columns=['Geography'])
X.head(10)

CreditScore  Gender  Age  ...  EstimatedSalary  Geography_1  Geography_2
0          619       0   42  ...        101348.88            0            0
1          608       0   41  ...        112542.58            0            1
2          502       0   42  ...        113931.57            0            0
3          699       0   39  ...         93826.63            0            0
4          850       0   43  ...         79084.10            0            1
5          645       1   44  ...        149756.71            0            1
6          822       1   50  ...         10062.80            0            0
7          376       0   29  ...        119346.88            1            0
8          501       1   44  ...         74940.50            0            0
9          684       1   27  ...         71725.73            0            0

[10 rows x 11 columns]

**Feature Standardization**

In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0, stratify = y)

In [0]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [22]:
X_train

array([[-1.24021723, -1.09665089,  0.77986083, ...,  1.64099027,
        -0.57812007, -0.57504086],
       [ 0.75974873,  0.91186722, -0.27382717, ..., -1.55587522,
         1.72974448, -0.57504086],
       [-1.72725557, -1.09665089, -0.9443559 , ...,  1.1038111 ,
        -0.57812007, -0.57504086],
       ...,
       [-0.51484098,  0.91186722,  0.87565065, ..., -1.01507508,
         1.72974448, -0.57504086],
       [ 0.73902369, -1.09665089, -0.36961699, ..., -1.47887193,
        -0.57812007, -0.57504086],
       [ 0.95663657,  0.91186722, -1.32751517, ...,  0.50945854,
        -0.57812007,  1.73900686]])

**Build ANN**

In [23]:
model = Sequential()
model.add(Dense(X.shape[1], activation='relu', input_dim = X.shape[1]))
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation = 'sigmoid'))

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [24]:
X.shape[1]

11

In [25]:
model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [26]:
# Model fitting
model.fit(X_train, y_train.to_numpy(), batch_size = 10, epochs = 10, verbose = 1)

Train on 8000 samples
Epoch 1/10
8000/8000 [==============================] - 2s 198us/sample - loss: 0.4462 - acc: 0.8052
Epoch 2/10
8000/8000 [==============================] - 1s 155us/sample - loss: 0.3919 - acc: 0.8374
Epoch 3/10
8000/8000 [==============================] - 1s 146us/sample - loss: 0.3555 - acc: 0.8528
Epoch 4/10
8000/8000 [==============================] - 1s 153us/sample - loss: 0.3474 - acc: 0.8564
Epoch 5/10
8000/8000 [==============================] - 1s 155us/sample - loss: 0.3437 - acc: 0.8574
Epoch 6/10
8000/8000 [==============================] - 1s 158us/sample - loss: 0.3396 - acc: 0.8587
Epoch 7/10
8000/8000 [==============================] - 1s 160us/sample - loss: 0.3366 - acc: 0.8610
Epoch 8/10
8000/8000 [==============================] - 1s 156us/sample - loss: 0.3353 - acc: 0.8614
Epoch 9/10
8000/8000 [==============================] - 1s 158us/sample - loss: 0.3332 - acc: 0.8612
Epoch 10/10
8000/8000 [==============================] - 1s 157us/sam

In [0]:
# Predict the classes
y_pred = model.predict_classes(X_test)

In [28]:
y_pred   # Print predict class.

array([[0],
       [0],
       [0],
       ...,
       [0],
       [1],
       [0]], dtype=int32)

In [29]:
y_test

1344    1
8167    0
4747    0
5004    1
3124    1
       ..
9107    0
8249    0
8337    0
6279    1
412     0
Name: Exited, Length: 2000, dtype: int64

In [30]:
model.evaluate(X_test, y_test.to_numpy())

2000/2000 [==============================] - 0s 30us/sample - loss: 0.3472 - acc: 0.8565


[0.3472354406118393, 0.8565]

In [0]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [32]:
confusion_matrix(y_test, y_pred)

array([[1544,   49],
       [ 238,  169]])

In [33]:
accuracy_score(y_test, y_pred)

0.8565

**Great Job SHivan!**